# Generated by Django 5.0.6 on 2024-07-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_theory',
            field=models.BooleanField(default=False),
        ),
    ]
