# Generated by Django 5.0.6 on 2024-07-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_expl_task_expl_img_task_expl_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertaskstatus',
            name='total_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
