# Generated by Django 5.0.6 on 2024-07-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_is_theory'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='expl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='expl_img',
            field=models.ImageField(blank=True, null=True, upload_to='task_images/'),
        ),
        migrations.AddField(
            model_name='task',
            name='expl_video',
            field=models.FileField(blank=True, null=True, upload_to='task_videos/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.CharField(default='6class', max_length=10),
        ),
    ]
