# Generated by Django 5.0.6 on 2024-08-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_usertaskstatus_total_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='task_files/'),
        ),
        migrations.AddField(
            model_name='task',
            name='file_link_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
